name: security-bear
base: core20
version: '1.1.1'  # Just for humans, typically '1.2+git' or '1.3.2'
summary: Easy way to connect to your devices for the first time through a WiFi. # 79 char long summary
description: |
  Allowing an easy and secure way to connect to your devices and IoT for maintenance through a WiFi network.

  * The software will connect to default WiFi credentials so that you will be able to connect to the devices even if they don't have a screen (you will change the default after connecting).

  * Set the number of WiFi credentials and the software will connect to them with the priority that you set.

  The software will try to connect to the following (default) WiFi

  WiFi name: `CyBear Jinni`

  WiFi password: `CyBear Jinni`

  Which you can create by opening a hotspot from your phone or laptop with these credentials.

  For interactions with the software you can use the CyBear Jinni App which is part of CyBear Jinni Smart Home.

  Our goal here at CyBear Jinni is to raise the quality of life for everyone.
  We are doing this by making Smart-Home accessible for the common person.

  This is an open-source project so feel free to take a look at the code and join us in advancing the world forward.

grade: stable  # devel/stable
confinement: strict  # devmode/classic/strict

architectures:
  - build-on: armhf
    run-on: armhf

  - build-on: arm64
    run-on: arm64

  - build-on: amd64
    run-on: amd64

parts:
  scripts-files:
    plugin: dump
    source: .
    override-build: |
      rm README.md

  security-bear:
    source: https://github.com/CyBear-Jinni/security_bear.git
    after:
      - scripts-files
    plugin: dump
    override-build: |
      mv ../../scripts-files/src/scripts .

      scripts/bashScripts/nativeExecutableMaker.sh  # Downloading dart-sdk for the correct architecture

      #  rm -r security_bear

      snapcraftctl build

    build-packages:
      - wget
      - unzip
      - git
    stage-packages:
      - crda
      - iputils-arping
      - iw
      - libbluetooth3
      - libcap2-bin
      - libfribidi0
      - libgudev-1.0-0
      - libjansson4
      - libmbim-glib4
      - libmbim-proxy
      - libmm-glib0
      - libndp0
      - libnewt0.52
      - libnl-3-200
      - libnl-genl-3-200
      - libnm0
      - libpam-cap
      - libpcap0.8
      - libpcsclite1
      - libpipeline1
      - libpolkit-agent-1-0
      - libpolkit-gobject-1-0
      - libqmi-glib5
      - libqmi-proxy
      - libslang2
      - libteamdctl0
      - libusb-1.0-0
      - modemmanager
      - policykit-1
      - ppp
      - pptp-linux
      - usb-modeswitch
      - usb-modeswitch-data
      - wireless-regdb
      - wpasupplicant
      - libatm1

      - network-manager-pptp
      - network-manager

      - wireless-tools

apps:
  security-bear:
    command: Security-Bear $SNAP
    daemon: simple
    plugs: [network, network-bind, network-manager, network-observe]
